# Project-level Gradle settings.
# Enables AndroidX support across all dependencies
android.useAndroidX=true

# Specifies the JVM arguments used for the Gradle Daemon (8GB RAM allocated).
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8

# Enables parallel execution and build caching for faster builds
org.gradle.parallel=true
org.gradle.caching=true
